#+TITLE: Universal Gates in Classical and Quantum Mechanics  
#+AUTHOR: Trent Fridey
#+DATE: 2020-12-22
#+HUGO_BASE_DIR: ~/trent/blog
#+HUGO_SECTION: posts/solovay-kitaev
#+HUGO_DRAFT: true
#+HUGO_TAGS: quantum physics programming
#+SUMMARY: Some superficial appraisals of quantum computing state that the difference between classical and quantum computing lies in the differences between a bit and a qubit. In this post, we compare the other fundamental entity of classical computing, the logic gate, to its quantum counterpart 

* Introduction

 Classical computers are based on /bits/, a set of binary variables $\{x_i | x \in \{0, 1\}\}$ and /logic gates/, which give classical computers their power.
 There are many logic gates but the NAND gate is a /universal/ gate for classical computing because it can implement any of the other gates.

In quantum computing, not all of the classical logical gates are available.
This is because, unlike most classical computers today, quantum computers must implement reversible computation[fn:1].
Further, quantum computers have additional logical gates not available to classical computers.
These include for example the Hadamard, Toffoli, and Z gates.

# Insert venn diagram of classical gates with quantum gates

Yet it is still desirable that we identify which of the gates available to quantum computers are universal.
In other words, we would like to identify the (quantum) gates which (when taken individually or as a set) can implement any of the other gates.

* Proving Universality

** Classical Computing
   
  In classical computing, we can prove that the NAND gate is capable of implementing any of the other logic gates by looking at its truth table:
  
 \begin{array}{c|c|c}
  x & y & !(x \land y)  \newline
  0 & 0 & 1 \newline
  0 & 1 & 1 \newline
  1 & 0 & 1 \newline
  1 & 1 & 0 \newline
 \end{array}
#+CAPTION: The truth table for the NAND gate

*** TODO prove that the NAND gate is universal
    :PROPERTIES:
    :Effort:   5
    :END:

** Quantum Computing

   In quantum computing, we work with qubits, which are vectors in $\mathbb{C}^2$ with unit norm.
   Single qubit gates are unitary matrices in $SU(2)$

*** TODO derive a proof of the universal gate set
    :PROPERTIES:
    :Effort:   8
    :END:
  
* TODO Solovay-Kitaev 
  :PROPERTIES:
  :Effort:   10
  :END:

* Footnotes

[fn:1] This is a constraint that comes from the fact that quantum logic gates must be /unitary/, which is comes from the fundamentals of quantum theory. 
