baseURL = "https://blog.trentfridey.com/"
languageCode = "en-us"
title = "The Derivation"
theme = "substance"
paginate=5
googleAnalytics = 'G-WVN0K5PQ62'
ignoreFiles = ["/posts/.*/ltximg"]
enableGitInfo = true
[params]
  math = true
  author = "Trent Fridey"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "algol"
    tabWidth = 4

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "All Tags"
url = "/tags"
weight = 4