baseURL = "https://blog.trentfridey.com/"
languageCode = "en-us"
title = "The Derivation"
theme = "substance"
paginate=5
googleAnalytics = 'G-WVN0K5PQ62'
ignoreFiles = ["/posts/.*/ltximg"]
enableGitInfo = true
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', '^NETLIFY_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
[params]
  math = true
  author = "Trent Fridey"
  images = ["favicon.svg"]
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "algol"
    tabWidth = 4

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "All Tags"
url = "/tags"
weight = 4
