baseURL = "https://blog.trentfridey.com/"
languageCode = "en-us"
title = "The Derivation"
theme = "substance"
paginate=5
ignoreFiles = ["/posts/.*/ltximg"]
[params]
  math = true
  author = "Trent Fridey"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4