#+TITLE: Homotopy, Homology, Holonomy 
#+AUTHOR: Trent Fridey
#+DATE: 2020-12-13
#+HUGO_BASE_DIR: ~/trent/blog
#+HUGO_SECTION: posts/homotopy-homology-holonomy
#+HUGO_TAGS: math physics differential-geometry

  
* Homotopy

  The geometric idea of homotopy is an interpolation between two paths on a manifold which share the same start and end point.

  [[file:images/homotopy.svg]]  
  
  Mathematically speaking, given a manifold $S$ and two fixed points $p$ and $q$ on the manifold, two paths $\gamma_0, \gamma_1 : [0,T] \to S$ are *homotopic* if there exists a smooth function $\gamma$:

  \[
  \gamma: [0,1] \times [0,T] \to S
  \]

  such that $\gamma(s, \cdot)$ is a path from $p$ to $q$ for each $s$ and

  \[
  \gamma(0,t) = \gamma_0(t) \qquad \gamma(1,t) = \gamma_1(t)
  \]
  
  Such a function $\gamma$ is a *homotopy* between $\gamma_0$ and $\gamma_1$.

  Things start to get interesting if we have a manifold where there is an obstruction to homotopy.
  This can happen if the manifold has 'holes' in it.
  
* (Co)Homology

  Cohomology is a way to study "holes" by looking at [[https://en.wikipedia.org/wiki/Differential_form][differential forms]] on manifolds.
  
  A differential $p$ -form $\omega$ is *closed* if $\mathrm{d}\omega = 0$
  A differential $p$ -form $\beta$ is *exact* if there exists some $p-1$ -form $\alpha$ such that $\beta = \mathrm{d}\alpha$.
   
  Note that all exact forms are closed:

  \[
  \mathrm{d}\beta = \mathrm{d}^{2}\alpha = 0
  \]

  But not all closed forms are exact.
  The reason this is true is that not every manifold is simply connected -- in other words, there are obstructions to /homotopy/.
  If $\Omega$ is not simply connected, then the integral of a closed form around a loop could be non-zero, which breaks Stokes theorem.

  

* Holonomy

The idea of a holonomy is a measure of the curvature of a manifold by inspecting the change in a vector as it is transported along a closed loop.
This geometric notion is best described through a picture:

[[file:images/holonomy.svg]]
  
The tangent vector $u$ is pushed along the loop $\gamma$ on the sphere $M$.
The progression is indicated by a change in color, from red to orange, yellow, green, to blue.
As it completes the loop, it ends up pointing in a different direction only because the sphere is curved.

  Mathematically speaking, if $\gamma: [0, T] \to M$ is a smooth path from $p$ to $q$ in the manifold $M$, and $E$ is a vector bundle with connection $D$, given $u \in E_p$, then

  \[
  H(\gamma, D)u
  \]

  is the result of parallel transporting $u$ to $q$ along path $\gamma$. The function $H(\gamma, D)$ is the *holonomy*.

* Application: Aharonov-Bohm Phase

Let the manifold $M$ be:
 
\[
M = \mathbb{R}^3 - \{(0,0,z) | z \in \mathbb{R} \}
\]

This is the usual three dimensional space, except there is a 'hole' along the vertical axis.

There is an obstruction to homotopy of the paths:

\[
\gamma_0(t) = (\cos(\pi t), \sin(\pi t), 0) \qquad \gamma_1(t) = (\cos(\pi t), -\sin(\pi t), 0)
\]

Which can be visualized below:

[[file:images/obstruction.svg]]

There's no way to smoothly deform $\gamma_1$ into $\gamma_2$ while keeping $p$ and $q$ fixed -- you can't get around the void at the origin!

In other words, we can find a 1-form $A$ such that:

\[
\oint_\gamma A \neq 0
\] 

for some smooth closed path $\gamma: [0,T] \to M$, $\gamma(0) = \gamma(T)$

If we form the $G$ -bundle $E = M \times V$ where $V$ is the vector space of the representation of the group $U(1)$, then the /holonomy/:

\[
H(\gamma, D)u = e^{i\oint_\gamma A} u
\]

describes the resulting wavefunction $u$ of a quantum particle after being parallel transported around a loop $\gamma$ in the base space.

Choosing $\gamma = (\cos(2\pi t), \sin(2\pi t), 0)$ as the path, and the one-form as:

$$
A = \frac{2\pi}{r}\mathrm{d}\theta
$$

Then $e^{i\oint_\gamma A}$ is the Aharonov-Bohm phase seen in the [[https://en.wikipedia.org/wiki/Aharonov%E2%80%93Bohm_effect][Aharonov-Bohm effect]].   
