#+TITLE: Spin Squeezing 
#+AUTHOR: Trent Fridey
#+DATE: 2020-10-10
#+HUGO_DRAFT: true
#+STARTUP: latexpreview
#+SUMMARY: In this post we look at the method of /spin squeezing/, which is a way to increase the precision of a quantum measurement by using entanglement.
#+HUGO_TAGS: quantum statistics physics
#+HUGO_BASE_DIR: ~/trent/blog
#+HUGO_SECTION: posts/spin-squeezing

* The Setup
  
  Let's consider a quantum system of $N$ spin-$1/2$ particles.
  These spins are prepared in a /coherent/ state:

  $$
  \left| \theta, \phi \right\rangle = \frac{1}{\sqrt{N}}\bigotimes_{i=1}^N  \left[
    \cos{\left(\frac{\theta}{2}\right)}|0\rangle +
    e^{i\phi}\sin\left({\frac{\theta}{2}}\right)|1\rangle
  \right]
  $$

** Bloch Sphere
  If we calculate the expected value of the total spin operator of this state:

  $$
  \vec{S} = \sum_{i=1}^N \vec{S}_i
  \qquad
  \vec{S}_i = \frac{1}{2}\left(\sigma^x_i \hat{x} + \sigma^y_i \hat{y} + \sigma^z_i \hat{z}\right) 
  $$

  we get a nice geometric result: 

  $$
  \left\langle \theta, \phi \right| \vec{S} \left| \theta, \phi \right\rangle =
  \frac{N}{2}\sin{\theta}\cos{\phi}\hat{x} + 
  \frac{N}{2}\sin{\theta}\sin{\phi}\hat{y} +
  \frac{N}{2}\cos{\theta}\hat{z}
  $$

  We can assign $\theta$ as the azimuthal angle and $\phi$ as the polar angle.
  Then we have the picture of a vector in 3D space, constrained to a sphere of radius $\frac{N}{2}$.
  Proceeding in this way, we call the direction this vector points the /mean spin direction/ or MSD.
  
  We can form a vector $\hat{n}_\perp$ which is perpendicular to the MSD such that $\langle \vec{S} \rangle \cdot \hat{n}_\perp = 0$  .
  If the tip of the $\langle \vec{S} \rangle$ vector can be represented by a point $(\theta_0, \phi_0)$ on a sphere, then the $\hat{n}_\perp$ vector can be thought of as being tangent to the sphere at this point.

  Because the vector $\langle\vec{S}\rangle$ is an expectation value, we can calculate the variance of it: $\Delta \vec{S}^2 = \left\langle \vec{S}\cdot\vec{S} \right\rangle - \left\langle \vec{S} \right\rangle^2$.
  We can also decompose the variance into the variance along the MSD (denoted by $\Delta \vec{S}_{\parallel}^2$) and perpendicular to the MSD (denoted by $\Delta \vec{S}_{\perp}^2$).

\[
\Delta \vec{S}^2 = \Delta \vec{S}_{\parallel}^2 + \Delta \vec{S}_{\perp}^2
\]
  
  From our definition of $\hat{n}_\perp$, the second term will be the variance along $\hat{n}_\perp$.

** Husimi Q-function

  If we calculate $\Delta \vec{S}_{\perp}$, we can relate it to another important measure of the coherent state: the /Husimi Q-function/, which is defined for a general spin state $|\psi\rangle$ as:

  $$
  Q(\theta, \phi) = |\langle \theta, \phi | \psi \rangle |^2
  $$
  
  
# Calculation of spread goes here
# Also include graphic on sphere
#+BEGIN_SRC python :var name="images/q-func.png" :results file
  import matplotlib.pyplot as plt
  import numpy as np
  from matplotlib import cm, colors
  import numpy as np
  from scipy.special import sph_harm

  phi = np.linspace(0, 2*np.pi, 100)
  theta = np.linspace(0, np.pi, 100)
  phi, theta = np.meshgrid(phi, theta)

  x = np.sin(theta) * np.cos(phi)
  y = np.sin(theta) * np.sin(phi)
  z = np.cos(theta)

  theta0, phi0 = np.pi/2, 0

  def q_func(theta0, phi0):
      return 1


  return name
  #+END_SRC

  
* Introducing Squeezing

** TODO Use plot of Husimi function to motivate squeezing

   We can get a better measurement by reducing the variance of the measurement.
   If variance = width of Q function, then decreasing width of Q-function should increase measurement precision.

*** TODO Catch: Heisenberg Uncertainty relation

    There is a tradeoff in this procedure, due to the way quantum mechanics works.
    It is quantified by the /Heisenberg uncertainty relation/:

    \[
    \Delta S_i \Delta S_j \geq \epsilon_{ijk}S_k
    \]

** Definition of Squeezing Operator

*** TODO Motivate definition with Mean field description

   How to induce a change in the Q-function?
   We only have the Pauli spin operators to work with, so we must construct a squeezing operator out of these.
   Any transformation must come from either a sum of single body operators or a sum of multi-body operators.
   The sum of single body operators induce rotations.
   Anything more than 2-body interactions may be complex.
   The simplest operator is a sum of 2-body operators..

   The spin squeezing operator is defined as:

   $$
   U(t) = \exp\left(-\frac{i}{2}t \sum_{i \neq j}^N \sigma^z_i\sigma^z_j\right) 
   $$

   This is called the /one-axis twisting/ operator in the literature.
   With this definition, we apply it to a coherent state $\left|\theta=0, \phi=\frac{\pi}{2} \right\rangle = |+x\rangle$ to  obtain the state:

   $$
   \left|\psi(t)\right\rangle = U(t)|+x\rangle
   $$

*** TODO connect with Q function
    
** Quantifying Squeezing

   We can quantify the degree that the state has been squeezed by comparing it to the initial state.
   We expect that a squeezed state should have a smaller variance in one direction than the initial state.

*** TODO introduce minimum variance spin operator

  \[
  \Delta S_{\text{min}}^2 = \min_{\hat{n}} \Delta \left(\vec{S}\cdot\hat{n}\right)^2
  \]
    
*** TODO define squeezing parameter 

* Numerical simulations
  
** Finding the Optimal Angle

*** TODO Use Python's autograd Library to Compute

    Implement squeezing parameter as a function of only numpy functions available to [[https://github.com/HIPS/autograd][autograd]]. 

* Footnotes

  Reference here:  https://arxiv.org/pdf/1011.2978.pdf
